# Site settings
permalink: /:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
title: Ifmicro-vim by MwumLi
email: mwumli@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mwumli.github.com/ifmicro-com" # the base hostname & protocol for your site
github_username:  MwumLi

# Build settings
markdown: kramdown
highlighter: pygments

# site info for your project
info:
    username: MwumLi
    projectname: ifmicro-vim
    branchname: master
    tagline: My vim configuration and plugin managing

google_analytics_code: 'UA-50450008-2'
